### ISSUE TITLE
Build fail ;cc

### ISSUE THREAD

**Issue by WhoAmI2704** [ZimnyCat/BigRat#6]
C:\Users\PC\Downloads\New folder\BigRat-master>gradlew build

> Configure project :
Fabric Loom: 0.8.21

> Task :compileJava
warning: Supported source version 'RELEASE_8' from annotation processor 'org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor' less than -source '16'
C:\Users\PC\Downloads\New folder\BigRat-master\src\main\java\bleach\hack\mixin\MixinCamera.java:16: warning: Cannot find target method for @Inject in net.minecraft.client.render.Camera
    @Inject(at = @At("HEAD"), method = "getSubmergedFluidState()Lnet/minecraft/fluid/FluidState;", cancellable = true)
    ^
C:\Users\PC\Downloads\New folder\BigRat-master\src\main\java\bleach\hack\mixin\MixinClientPlayerEntity.java:111: warning: Unable to determine signature for @Inject target method
    @Inject(at = @At("HEAD"), method = "method_30673", cancellable = true)
    ^
C:\Users\PC\Downloads\New folder\BigRat-master\src\main\java\bleach\hack\mixin\MixinIngameHud.java:41: warning: Cannot find target method for @Inject in net.minecraft.client.gui.hud.InGameHud
    @Inject(at = @At("HEAD"), method = "renderPumpkinOverlay()V", cancellable = true)
    ^
C:\Users\PC\Downloads\New folder\BigRat-master\src\main\java\bleach\hack\mixin\MixinMinecraftClient.java:32: warning: Cannot find target method for @Inject in net.minecraft.client.MinecraftClient
    @Inject(at = @At("HEAD"), method = "openScreen(Lnet/minecraft/client/gui/screen/Screen;)V", cancellable = true)
    ^
C:\Users\PC\Downloads\New folder\BigRat-master\src\main\java\bleach\hack\mixin\MixinSkyProperties.java:14: warning: Unable to determine signature for @Inject target method
    @Inject(at = @At("HEAD"), method = "getSkyColor", cancellable = true)
    ^
warning: Supported source version 'RELEASE_8' from annotation processor 'org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor' less than -source '16'
C:\Users\PC\Downloads\New folder\BigRat-master\src\main\java\bleach\hack\mixin\MixinSharedConstants.java:14: warning: @Overwrite is missing javadoc comment
    public static boolean isValidChar(char chr) {
                          ^
C:\Users\PC\Downloads\New folder\BigRat-master\src\main\java\bleach\hack\command\commands\CmdEnchant.java:25: error: cannot find symbol
import net.minecraft.nbt.CompoundTag;
                        ^
  symbol:   class CompoundTag
  location: package net.minecraft.nbt
C:\Users\PC\Downloads\New folder\BigRat-master\src\main\java\bleach\hack\command\commands\CmdEnchant.java:26: error: cannot find symbol
import net.minecraft.nbt.ListTag;
                        ^
  symbol:   class ListTag
  location: package net.minecraft.nbt
C:\Users\PC\Downloads\New folder\BigRat-master\src\main\java\bleach\hack\command\commands\CmdNBT.java:23: error: cannot find symbol
import net.minecraft.nbt.CompoundTag;
                        ^
  symbol:   class CompoundTag
  location: package net.minecraft.nbt
C:\Users\PC\Downloads\New folder\BigRat-master\src\main\java\bleach\hack\command\commands\CmdRbook.java:24: error: cannot find symbol
import net.minecraft.nbt.ListTag;
                        ^
  symbol:   class ListTag
  location: package net.minecraft.nbt
C:\Users\PC\Downloads\New folder\BigRat-master\src\main\java\bleach\hack\command\commands\CmdRbook.java:25: error: cannot find symbol
import net.minecraft.nbt.StringTag;
                        ^
  symbol:   class StringTag
  location: package net.minecraft.nbt
C:\Users\PC\Downloads\New folder\BigRat-master\src\main\java\bleach\hack\command\commands\CmdSkull.java:23: error: cannot find symbol
import net.minecraft.nbt.CompoundTag;
                        ^
  symbol:   class CompoundTag
  location: package net.minecraft.nbt
C:\Users\PC\Downloads\New folder\BigRat-master\src\main\java\bleach\hack\gui\widget\BleachCheckbox.java:22: error: cannot find symbol
import net.minecraft.client.gui.widget.AbstractPressableButtonWidget;
                                      ^
  symbol:   class AbstractPressableButtonWidget
  location: package net.minecraft.client.gui.widget
C:\Users\PC\Downloads\New folder\BigRat-master\src\main\java\bleach\hack\gui\widget\BleachCheckbox.java:29: error: cannot find symbol
public class BleachCheckbox extends AbstractPressableButtonWidget {
                                    ^
  symbol: class AbstractPressableButtonWidget
C:\Users\PC\Downloads\New folder\BigRat-master\src\main\java\bleach\hack\module\mods\AutoDonkeyDupe.java:24: error: cannot find symbol
import net.minecraft.network.packet.c2s.play.PlayerInteractEntityC2SPacket.InteractionType;
                                                                          ^
  symbol:   class InteractionType
  location: class PlayerInteractEntityC2SPacket
C:\Users\PC\Downloads\New folder\BigRat-master\src\main\java\bleach\hack\module\mods\BookCrash.java:30: error: cannot find symbol
import net.minecraft.nbt.CompoundTag;
                        ^
  symbol:   class CompoundTag
  location: package net.minecraft.nbt
C:\Users\PC\Downloads\New folder\BigRat-master\src\main\java\bleach\hack\module\mods\BookCrash.java:31: error: cannot find symbol
import net.minecraft.nbt.ListTag;
                        ^
  symbol:   class ListTag
  location: package net.minecraft.nbt
C:\Users\PC\Downloads\New folder\BigRat-master\src\main\java\bleach\hack\module\mods\BookCrash.java:32: error: cannot find symbol
import net.minecraft.nbt.StringTag;
                        ^
  symbol:   class StringTag
  location: package net.minecraft.nbt
C:\Users\PC\Downloads\New folder\BigRat-master\src\main\java\bleach\hack\module\mods\MountBypass.java:9: error: cannot find symbol
import net.minecraft.network.packet.c2s.play.PlayerInteractEntityC2SPacket.InteractionType;
                                                                          ^
  symbol:   class InteractionType
  location: class PlayerInteractEntityC2SPacket
C:\Users\PC\Downloads\New folder\BigRat-master\src\main\java\bleach\hack\module\mods\NoSlow.java:30: error: package net.minecraft.client.options does not exist
import net.minecraft.client.options.KeyBinding;
                                   ^
C:\Users\PC\Downloads\New folder\BigRat-master\src\main\java\bleach\hack\utils\ItemContentUtils.java:23: error: cannot find symbol
import net.minecraft.nbt.CompoundTag;
                        ^
  symbol:   class CompoundTag
  location: package net.minecraft.nbt
C:\Users\PC\Downloads\New folder\BigRat-master\src\main\java\bleach\hack\utils\ItemContentUtils.java:24: error: cannot find symbol
import net.minecraft.nbt.ListTag;
                        ^
  symbol:   class ListTag
  location: package net.minecraft.nbt
C:\Users\PC\Downloads\New folder\BigRat-master\src\main\java\bleach\hack\utils\WorldRenderUtils.java:26: error: cannot find symbol
import net.minecraft.client.util.math.Vector3f;
                                     ^
  symbol:   class Vector3f
  location: package net.minecraft.client.util.math
17 errors
8 warnings

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/7.0.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 4s
1 actionable task: 1 executed

**Comment by ZimnyCat** [comment]
im working on 1.17.1 update

**Comment by KnightxMare** [comment]
Same Problem with me

**Comment by WhoAmI2704** [comment]
;c

**Comment by ZimnyCat** [comment]
soon

**Comment by ZimnyCat** [comment]
1.17 canceled because Java 16 broke everything
